package pe.devpicon.android.mytestinglabapp

object Constants{
    const val ORDERS_NOTIFICATION_CHANNEL_ID = "ORDERS_NOTIFICATION_CHANNEL"
    const val ORDERS_ASSIGNMENTS_NOTIFICATION_CHANNEL_ID = "ORDERS_ASSIGNMENTS_NOTIFICATION_CHANNEL_ID"
    const val ORDERS_ASSIGNMENTS_NOTIFICATION_CHANNEL_ID_2 = "ORDERS_ASSIGNMENTS_NOTIFICATION_CHANNEL_ID_2"
}